export const apiData = [
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '1',
    },
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '2',
    },
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '3',
    },
        {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '4',
    },
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '5',
    },
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '6',
    },    
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '7',
    },
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '8',
    },
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '9',
    },
        {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '10',
    },
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '11',
    },
    {
      product: "https://via.placeholder.com/150",
      name: "Under Urmer",
      price: 300,
      quantity: 4,
      id: '12',
    }
  ]